---
title: "Cytokine Resistance Phosphodata"
author: "Michael Nestor"
date: "8/3/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
##process cytokine data
library(amlresistancenetworks)
library(dplyr)
```

```{r}
# load data
globalData <- querySynapseTable('syn22986326') %>%
  subset(!is.nan(LogRatio)) %>%
  mutate(Gene = unlist(Gene))

phosData <- querySynapseTable('syn22986341') %>%
  subset(!is.nan(LogRatio)) %>%
  mutate(Gene = unlist(Gene)) %>%
  mutate(site = unlist(site))


clinvars<-phosData %>%
  dplyr::select(Sample = 'sample', CellType, TimePoint, Treatment, Batch) %>%
  distinct()

summary <- phosData %>%
  dplyr::select(sample, CellType, TimePoint, Treatment) %>%
  distinct() %>%
  mutate(conditionName = stringr::str_c(CellType, TimePoint, Treatment,
                                        sep = '_'))

print(summary)

phosMat <- phosData %>%
  dplyr::select(sample, site, LogRatio) %>%
  tidyr::pivot_wider(values_from = LogRatio, names_from = sample,
                     values_fn = list(LogRatio = mean, na.rm=T),
                     values_fill = list(LogRatio = 0.0)) %>%
  tibble::remove_rownames() %>%
  tibble::column_to_rownames('site')
```

```{r}
# 1- remove all patients with Treatment='Trametinib Withdrawn'
globalData <- globalData %>% filter(Treatment != "Trametinib Withdrawn")
phosData   <- phosData   %>% filter(Treatment != "Trametinib Withdrawn")
```

```{r}
# 2- Create PCA plots of global and phospho for the late molm13 only, and the late molm 13 + parental

#' @param dat.table
plotAllData <- function(dat.table) {
  library(ggfortify)
  met <- dat.table %>%
    dplyr::select(sample, CellType, TimePoint, Treatment) %>%
    distinct()
    
  mat <- dat.table %>% dplyr::select(Gene,LogRatio,sample) %>%
    distinct() %>%
    mutate(LogRatio=as.numeric(LogRatio)) %>%
    tidyr::pivot_wider(names_from='sample', values_from='LogRatio',
                       values_fn=list(LogRatio=function(x) mean(x,na.rm=T)),
                       values_fill=list(LogRatio=0)) %>%
    tibble::remove_rownames() %>%
    tibble::column_to_rownames('Gene')
  mat <- mat[complete.cases(mat),]
  autoplot(prcomp(t(mat)), data=met, colour='Treatment', shape='CellType')
 
}

# global PCA

output_dir <- "./pca_plots"
if (!dir.exists(output_dir)) dir.create(output_dir)
pdf(file.path(output_dir, "Late_MOLM13_only_global_PCA.pdf"))
globalData %>% filter(Batch == "Experiment 2") %>%
  filter(CellType == "Late MOLM-13") %>%
  plotAllData() +
  ggtitle("Global PCA, Late MOLM-13 Only")
dev.off()

pdf(file.path(output_dir, "Late_MOLM13_w_Parental_global_PCA.pdf"))
globalData %>% filter(Batch == "Experiment 2") %>%
  plotAllData() +
  ggtitle("Global PCA, Late MOLM-13 + Parental")
dev.off()

# phospho PCA
pdf(file.path(output_dir, "Late_MOLM13_only_phospho_PCA.pdf"))
phosData %>% filter(Batch == "Experiment 2") %>%
  filter(CellType == "Late MOLM-13") %>%
  plotAllData() +
  ggtitle("Phospho PCA, Late MOLM-13 Only")
dev.off()
  
pdf(file.path(output_dir, "Late_MOLM13_w_Parental_phospho_PCA.pdf"))
phosData %>% filter(Batch == "Experiment 2") %>%
  plotAllData() +
  ggtitle("Phospho PCA, Late MOLM-13 + Parental")
dev.off()

```



## KSEA enrichment analysis
```{r ksea, echo=FALSE}
#' plot all the KSEA 
#' @param condList
#' @return data frame
#' @importsFrom dplyr %>% distinct mutate left_join select 
#' @importsFrom stringr str_replace str_replace_all
#' @importsFrom purrr map_df
#' @importsFrom tibble rownames_to_column
#' @importsFrom amlresistancenetworks computeKSEA

library(stringr)
library(dplyr)
library(tibble)
library(purrr)

doAllKSEAplots <- function(condList, pdat, output_dir) {
  gene.to.site <- pdat %>%
    distinct(Gene, site, Peptide) %>%
    mutate(residue = str_replace(site, Gene, "" )) %>%
    mutate(residue = str_replace_all(residue,"([STY])", ";\\1")) %>%
    mutate(residue = str_replace(residue,"^;", "")) %>%
    mutate(residue = str_replace_all(residue,"([sty])", ""))
  
  setwd(output_dir)
  full.df <- purrr::map_df(names(condList), .f = function(clName) { 
    condList[[clName]] %>%
      rownames_to_column('site') %>%
      left_join(gene.to.site) %>%
      select(Gene, Peptide, residue, value='logFC', p_adj='adj.P.Val') %>%
      amlresistancenetworks::computeKSEA(., prefix = clName, 0.05) %>%
      mutate(Condition = clName) %>%
      as.data.frame()
  })
  
  return(full.df)
}

compare_samples <- function(phosMat, clinvars, treatment_A, treatment_B) {
  A_samples <- clinvars %>% filter(Batch == "Experiment 1") %>%
    filter(Treatment == treatment_A) %>% # question: is Molm-13 Tr-Resistant ok to use here?
    pull(Sample)
  B_samples <- clinvars %>% filter(Batch == "Experiment 1") %>%
    filter(Treatment == treatment_B) %>% 
    pull(Sample)
  limmaTwoFactorDEAnalysis(phosMat, A_samples, B_samples)
}

limma_DEA_results <- list(Tr_vs_Parental = compare_samples(phosMat, clinvars,
                                                   "Trametinib",       "none"),
                TrMCP1_vs_Parental = compare_samples(phosMat, clinvars,
                                                   "Trametinib+MCP-1", "none"),
                Tr_vs_TrMCP1 = compare_samples(phosMat, clinvars,
                                                   "Trametinib",       "Trametinib+MCP-1"))


output_dir <- "./ksea_plots"
if (!dir.exists(output_dir)) dir.create(output_dir)

KSEA_plots_output <- doAllKSEAplots(limma_DEA_results, phosData, output_dir = "./ksea_plots")
```


## Phospho data kinase enrichment

For this analysis will load in the phosphoproteomic data collected in the Molm13 cell lines. We use the 
stoichiometry corrected proteomic data to focus explicitly on the changes in kinase activity. 



## Now we can define the processing functions needed

We can plot the data and the kinase activity
```{r processing functions}


##plot kinase activity
plotKinDat <- function(kindat,sig.kin=NULL,prefix='all') {
  library(pheatmap)
  
  ##create matrix of kinase scores
  if (!is.null(sig.kin)) {
    kindat <- subset(kindat,Kinase %in% sig.kin$Kinase.Gene)
    kinmat <- sig.kin %>% mutate(score='Yes') %>%
      tidyr::pivot_wider(names_from=Condition,values_from=score,values_fill=list(score='No')) %>%
      tibble::column_to_rownames('Kinase.Gene')
    kinAts=kinmat
  } else {
    kinAts<-kindat%>%
      ungroup() %>%
      dplyr::select(Kinase,numSubstr) %>%
      distinct() %>%
      group_by(Kinase) %>%
      summarize(substrates=mean(numSubstr)) %>%
      tibble::remove_rownames() %>%
      tibble::column_to_rownames('Kinase')
  }
  
  mat <- kindat %>%
    ungroup() %>%
    tidyr::pivot_wider(-c(meanNKINscore, numSubstr),
                       values_from=meanLFC,
                       names_from=Sample,
                       values_fn=list(meanLFC=mean), values_fill=0.0) %>%
    tibble::remove_rownames() %>%
    tibble::column_to_rownames('Kinase')
  
  sampAts <- phosData %>%
    dplyr::select(sample,TimePoint,Treatment,CellType) %>%
    distinct() %>%
    tibble::remove_rownames() %>%
    tibble::column_to_rownames('sample')
  
  sampAts$TimePoint = as.factor(sampAts$TimePoint)
  mat <- as.matrix(mat)[rownames(kinAts),rownames(sampAts)]
  #vars=names(sort(apply(mat,1,var,na.rm=T),decreasing=T))
  pheatmap::pheatmap(mat, cellwidth = 8, cellheight=8, clustering_distance_cols = 'correlation',
          clustering_distance_rows = 'correlation',
          annotation_row = kinAts, annotation_col=sampAts) 

  pheatmap::pheatmap(mat, cellwidth = 8, cellheight=8, clustering_distance_cols = 'correlation',
          clustering_distance_rows = 'correlation',
          annotation_row = kinAts, annotation_col=sampAts,
          file=paste0(prefix, 'cytokineKinaseHeatmap.pdf'), height=8, width=10) 
}


kindat<-mapPhosphoToKinase(dplyr::rename(phosData, Sample='sample', LogFoldChange='LogRatio'))

sig.kin <- KSEA_plots_output %>%
  filter(p.value < 0.05) %>%
  distinct(Kinase.Gene,Condition) %>%
  
print(sig.kin)
  
plotKinDat(kindat, sig.kin, './ksea_plots/lateOnly')
```

